weight = 2
# 网站语言, 仅在这里 CN 大写
languageCode = "it"
# 语言名称
languageName = "Italiano"
# 是否包括中日韩文字
hasCJKLanguage = false
# 版权描述，仅仅用于 SEO
#copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
