# Multilingual config
# 多语言配置

[en]
  weight = 1
  # language code
  languageCode = "en"
  # language name
  languageName = "English"
  # whether to include Chinese/Japanese/Korean
  hasCJKLanguage = false
  # default amount of posts in each pages
  paginate = 12
  # copyright description used only for seo schema
  #copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[it]
  weight = 2
  # 网站语言, 仅在这里 CN 大写
  languageCode = "it"
  # 语言名称
  languageName = "Italiano"
  # 是否包括中日韩文字
  hasCJKLanguage = false
  # 默认每页列表显示的文章数目
  paginate = 12
  # 版权描述，仅仅用于 SEO
  #copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
