# Menu config
# 菜单配置

[[main]]
  identifier = "posts"
  pre = ""
  post = ""
  name = "Posts"
  url = "/posts/"
  title = ""
  weight = 1
[[main]]
  identifier = "categories"
  pre = ""
  post = ""
  name = "Categories"
  url = "/categories/"
  title = ""
  weight = 2
[[main]]
  identifier = "about"
  pre = ""
  post = ""
  name = "About me"
  url = "/about/"
  title = ""
  weight = 3