# website title
# 网站标题
title = "appsec.space"
# DoIt theme version
# DoIt 主题版本
version = "0.4.X"
# site default theme ("light", "dark", "black", "auto")
# 网站默认主题 ("light", "dark", "black", "auto")
defaultTheme = "auto"
# public git repo url only then enableGitInfo is true
# 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
gitRepo = "https://github.com/homazawa/himazawa.github.io"
# which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
# 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
fingerprint = "sha512"
# date format
# 日期格式
dateFormat = "2006-01-02"
# website images for Open Graph and Twitter Cards
# 网站图片, 用于 Open Graph 和 Twitter Cards
images = ["/images/logo.png"]
# enable PWA
# 开启 PWA 支持
enablePWA = false
# license information
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
# [Experimental] Bundle js
bundle = false
# Header config
# 页面头部导航栏配置
[header]
  # desktop header mode ("fixed", "normal", "auto")
  # 桌面端导航栏模式 ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  # 移动端导航栏模式 ("fixed", "normal", "auto")
  mobileMode = "auto"
  # theme change mode ("switch", "select")
  # 主题切换模式 ("switch", "select")
  themeChangeMode = "select"
  # Header title config
  # 页面头部导航栏标题配置
  [header.title]
    # URL of the LOGO
    # LOGO 的 URL
    logo = "/images/circle_cropped_logo.png"
    # title name
    # 标题名称
    name = ""
    # you can add extra information before the name (HTML format is supported), such as icons
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    # whether to use typeit animation for title name
    # 是否为标题显示打字机动画
    typeit = false

# Footer config
# 页面底部信息配置
[footer]
  enable = false
  # Custom content (HTML format is supported)
  # 自定义内容 (支持 HTML 格式)
  custom = ''
  # whether to show Hugo and theme info
  # 是否显示 Hugo 和主题信息
  hugo = false
  # Hosted on (HTML format is supported)
  # 托管服务信息 (支持 HTML 格式)
  # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
  hostedOn = '' 
  # whether to show copyright info
  # 是否显示版权信息
  copyright = true
  # whether to show the author
  # 是否显示作者
  author = true
  # site creation time
  # 网站创立年份
  since = 2023
  # ICP info only in China (HTML format is supported)
  # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
  icp = ""
  # license info (HTML format is supported)
  # 许可协议信息 (支持 HTML 格式)
  license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Section (all posts) page config
# Section (所有文章) 页面配置
[section]
  # special amount of posts in each section page
  # section 页面每页显示文章数量
  paginate = 20
  # date format (month and day)
  # 日期格式 (月和日)
  dateFormat = "01-02"
  # amount of RSS pages
  # RSS 文章数目
  rss = 10
  # recently updated posts settings
  # 最近更新文章设置
  [section.recentlyUpdated]
    enable = true
    rss = true
    days = 30
    maxCount = 10

# List (category or tag) page config
# List (目录或标签) 页面配置
[list]
  # special amount of posts in each list page
  # list 页面每页显示文章数量
  paginate = 20
  # date format (month and day)
  # 日期格式 (月和日)
  dateFormat = "01-02"
  # amount of RSS pages
  # RSS 文章数目
  rss = 10

# Page config
# 文章页面配置
[page]
  # whether to hide a page from home page
  # 是否在主页隐藏一篇文章
  hiddenFromHomePage = false
  # whether to hide a page from search results
  # 是否在搜索结果中隐藏一篇文章
  hiddenFromSearch = false
  # whether to enable twemoji
  # 是否使用 twemoji
  twemoji = false
  # whether to enable lightgallery
  # 是否使用 lightgallery
  lightgallery = false
  # whether to enable the ruby extended syntax
  # 是否使用 ruby 扩展语法
  ruby = true
  # whether to enable the fraction extended syntax
  # 是否使用 fraction 扩展语法
  fraction = true
  # whether to show link to Raw Markdown content of the content
  # 是否显示原始 Markdown 文档内容的链接
  linkToMarkdown = true
  # whether to show the full text content in RSS
  # 是否在 RSS 中显示全文内容
  rssFullText = true
  # Page style ("normal", "wide")
  # 页面样式 ("normal", "wide")
  # whether to enable series navigation
  # 是否使用系列导航
  seriesNavigation = true
  # Display a message at the beginning of an article to warn the reader that its content might be outdated.
  # 在文章开头显示提示信息，提醒读者文章内容可能过时。
  [page.outdatedArticleReminder]
    enable = false
    # Display the reminder if the last modified time is more than 90 days ago.
    # 如果文章最后更新于这天数之前，显示提醒
    reminder = 90
    # Display warning if the last modified time is more than 180 days ago.
    # 如果文章最后更新于这天数之前，显示警告
    warning = 180
  # Table of the contents config
  # 目录配置
  [page.toc]
    # whether to enable the table of the contents
    # 是否使用目录
    enable = true
    # whether to keep the static table of the contents in front of the post
    # 是否保持使用文章前面的静态目录
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    # 是否使侧边目录自动折叠展开
    auto = true
  # Code config
  # 代码配置
  [page.code]
    # whether to show the copy button of the code block
    # 是否显示代码块的复制按钮
    copy = true
    # the maximum number of lines of displayed code by default
    # 默认展开显示的代码行数
    maxShownLines = 10
  # Table config
  # 表格配置
  [page.table]
    # whether to enable sorting in the tables
    # 是否开启表格排序
    sort = true
  [page.header]
    # whether to enable auto header numbering
    # 是否开启标题自动编号
    [page.header.number]
      enable = true
      [page.header.number.format]
        h2 = "{h2} {title}"
        h3 = "{h2}.{h3} {title}"
        h4 = "{h2}.{h3}.{h4} {title}"
        h5 = "{h2}.{h3}.{h4}.{h5} {title}"
        h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
  # KaTeX mathematical formulas config (KaTeX https://katex.org/)
  # KaTeX 数学公式配置 (KaTeX https://katex.org/)
  [page.math]
    enable = false
  [page.share]
    enable = false
[search]
  enable = true
  # type of search engine ("algolia", "fuse")
  # 搜索引擎的类型 ("algolia", "fuse")
  type = "fuse"
  # max index length of the chunked content
  # 文章内容最长索引长度
  contentLength = 4000
  # placeholder of the search bar
  # 搜索框的占位提示语
  placeholder = ""
  # max number of results length
  # 最大结果数目
  maxResultLength = 10
  # snippet length of the result
  # 结果内容片段长度
  snippetLength = 300
  # HTML tag name of the highlight part in results
  # 搜索结果中高亮部分的 HTML 标签
  highlightTag = "em"
  # whether to use the absolute URL based on the baseURL in search index
  # 是否在搜索索引中使用基于 baseURL 的绝对路径
  absoluteURL = false
  [search.fuse]
    # https://fusejs.io/api/options.html
    isCaseSensitive = false
    minMatchCharLength = 2
    findAllMatches = true
    location = 0
    threshold = 0.1
    distance = 100
    ignoreLocation = true
    useExtendedSearch = false
    ignoreFieldNorm = false
# Home page config
# 主页信息设置
[home]
  # amount of RSS pages
  # RSS 文章数目
  rss = 10
  # Home page profile
  # 主页个人信息
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    # Gravatar 邮箱，用于优先在主页显示的头像
    gravatarEmail = ""
    # URL of avatar shown in home page
    # 主页显示头像的 URL
    avatarURL = "/images/logo.png"
    # title shown in home page (HTML format is supported)
    # 主页显示的网站标题 (支持 HTML 格式)
    title = ""
    # subtitle shown in home page
    # 主页显示的网站副标题
    subtitle = "A space where I talk about Application Security & other stuff"
    # whether to use typeit animation for subtitle
    # 是否为副标题显示打字机动画
    typeit = false
    # whether to show social links
    # 是否显示社交账号
    social = true
    # disclaimer (HTML format is supported)
    # 免责声明 (支持 HTML 格式)
    disclaimer = "Opinions are my own"
  # Home page posts
  # 主页文章列表
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    # 主页每页显示文章数量
    paginate = 7
# Social config in home page
# 主页的社交信息设置
[social]
  GitHub = "himazawa"
  RSS = true
  [social.Mastodon]
    id = "@himazawa"
    prefix = "https://infosec.exchange/"
